version: "3.9"
services:
  neo4j:
    image: neo4j:5.23
    ports: ["7474:7474", "7687:7687"]
    environment:
      NEO4J_AUTH: ${NEO4J_USER}-${NEO4J_PASSWORD}
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 2G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
